[package]
name = "yew_plotly_01"
version = "0.1.0"
edition = "2024"

[dependencies]
plotly = { version = "0.12", features = ["wasm"] }
yew = "0.21"
yew-hooks = "0.3"
log = "0.4"
wasm-logger = "0.2"
web-sys = { version = "0.3.77"}
